config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/terms_of_service'
  resources :users, only: %i[new create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles,only: %i[index new create show edit update destroy] do
    collection do
      get :search
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :article_likes, only: %i[create destroy]
  namespace :admin do
    root "articles#index"
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => "user_sessions#create"
    delete 'logout' => 'user_sessions#destroy', :as => :logout
    resources :articles, only: %i[new index edit update show destroy create]
  end
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'articles#index'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :question_body, presence: true, length: { maximum: 535 }
  validates :question_answer, length: { maximum: 535 }

  #ユーザーとの関連付け
  belongs_to :user

  #ブックマーク機能との関連付け
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks

  #いいね機能との関連付け
  has_many :article_likes, dependent: :destroy
  has_many :like_by_users, through: :article_likes, source: :user
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show;end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit;end

  # POST /articles or /articles.json
  def create
    @article = Article.build(article_params)

      if @article.save
        redirect_to admin_articles_path, notice: "Article was successfully created." 
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
      if @article.update(article_params)
        redirect_to admin_article_path(@article), notice: "Article was successfully updated."
      else
        flash.now[:danger] = '更新に失敗しました'
        render :edit, status: :unprocessable_entity
      end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!
      redirect_to admin_articles_path, notice: "Article was successfully destroyed.",status: :see_other 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :question_body, :question_answer)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
    @total_likes = @article.article_likes.count
  end

  def new
    @article = Article.new
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def create
    @article = current_user.articles.build(article_params)

      if @article.save
        UserMailer.new_article_notification(@article).deliver_later
        redirect_to article_url(@article), notice: "質問・回答を作成しました" 
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
    @article = current_user.articles.find(params[:id])
      if @article.update(article_params)
        redirect_to article_url(@article), notice: "質問・回答を更新しました"
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy!
      redirect_to articles_url, notice: "質問・回答を削除しました" 
  end

  def bookmarks
    @q = current_user.bookmark_articles.ransack(params[:q])
    @bookmark_articles = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(20)
  end

  def search
    @articles = Article.where("title like ?", "%#{params[:q]}%")

    respond_to do |format|
      format.js
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :question_body, :question_answer)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
    <tbody>
      <tr>
        <td><%= article.title%></td>
        <td><%= article.question_body%></td>
        <td><%= article.question_answer%></td>
        <td><%= article.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= article.updated_at.strftime("%Y-%m-%d") %></td>
        <% if defined?(@articles)%>
        <td>
        <%= button_to "詳細", article, method: :get, class: "btn btn-primary", type: "button"%>
        </td>
        <% end%>
      </tr>
      <!-- Add more rows for other articles -->
    </tbody>
</div>

app/views/articles/_bookmark_buttons.html.erb
<div class='ms-auto'>
  <% if current_user.bookmark?(article)%>
    <%= render 'unbookmark', { article: article } %>
  <% else %>
    <%= render 'bookmark', { article: article} %>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |f| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title,"質問タイトル", style: "display: block" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :question_body,"質問内容", style: "display: block" %>
    <%= f.text_area :question_body %>
  </div>
  <%if current_user.admin?%>
  <div>
    <%= f.label :question_answer,"質問回答", style: "display: block" %>
    <%= f.text_area :question_answer %>
  </div>
  <%end%>

  <div>
    <%= f.submit "投稿する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_like.html.erb
<%= link_to article_likes_path(article_id: article.id), id: "like-button-for-article-#{article.id}", data: { turbo_method: :post} do %>
  <i class = "bi bi-hand-thumbs-up"></i>
<% end %>

app/views/articles/_like_buttons.html.erb
<div class="ms-auto" id = "like-buttons">
  <% if current_user.liked?(article) %>
    <%= render 'unlike', { article: article} %>
  <% else %>
    <%= render 'like', { article: article} %>
  <% end %>
</div>

app/views/articles/_search_form.html.erb
<%=search_form_for @q, url: url, remote: true do |f| %>
  <div data-controller="autocomplete" data-autocomplete-url-value="articles/search" role="combobox">
  <div class="input-group mb-3">
    <%=f.search_field :title_cont, data: { autocomplete_target: 'input' },class: 'form-control', placeholder: '検索ワード'%>
    <%= f.hidden_field :title, data: { autocomplete_target: 'hidden' } %>
  <div class="input-group-append">
    <%=f.submit '検索', class: 'btn btn-primary'%>
  </div>
  </div>
<%end%>

app/views/articles/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(article_id: article.id)), id: "unbookmark-button-for-article-#{article.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-star-fill"></i>
<% end %>

app/views/articles/_unlike.html.erb
<%= link_to article_like_path(current_user.article_likes.find_by(article_id: article.id)), id: "unlike-button-for-article-#{article.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-hand-thumbs-up-fill"></i>
<% end %>

app/views/articles/bookmarks.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
       <%= render 'search_form', q: @q, url: bookmarks_articles_path %>
    </div>
  </div>
  <h2>お気に入り質問一覧</h2>
  <!-- 掲示板一覧 -->
        <% if @bookmark_articles.present? %>
        <table class="table table-striped table-bordered">
        <thead class="thead-dark">
        <tr>
          <th>質問タイトル</th>
          <th>質問内容</th>
          <th>質問回答</th>
          <th>質問作成日</th>
          <th>質問更新日</th>
        </tr>
      </thead>
          <tbody>
            <% @bookmark_articles.each do |article| %>
                <tr>
                <td><%= article.title %></td>
                <td><%= article.question_body %></td>
                <td><%= article.question_answer %></td>
                <td><%= article.created_at.strftime("%Y-%m-%d") %></td>
                <td><%= article.updated_at.strftime("%Y-%m-%d") %></td>
                <td>
                 <%= button_to "詳細", article, method: :get, class: "btn btn-primary", type: "button"%>
                </td>
                </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
  </div>
  <%= paginate @bookmark_articles, theme: 'bootstrap-5' %>

app/views/articles/edit.html.erb
<h1>質問編集</h1>
<div class="card">
   <div class="card-header">
    質問詳細
  </div>
  <div class="card-body">
    <h5 class="card-title">石綿産廃に関する質問詳細</h5>
<%= render "form", article: @article %>
  </div>
<div class="card-footer">
  <%= link_to "詳細画面へ", @article, class: "btn btn-primary" %>
  <%= link_to "一覧画面へ", articles_path, class: "btn btn-primary" %>
</div>
</div>

app/views/articles/index.html.erb
<div id="articles">
<div class="container mt-4">
<p style="color: green"><%= notice %></p>
  <h2>このサイトについて</h2>
  <p class = my-3>近年プラスチック、ごみ、地球温暖化など社会問題となっている環境問題ですが、その中でも2020年アスベストに関する新しいルールが制定されました。<br>
分かりづらい環境対策の知識、このサイトは主に石綿と廃棄物に焦点を当てて、すぐに実務に活かせるような情報をすぐに検索できるようになっています。</p>

    <h2 class="mb-4">質問記事一覧</h2>
    <%= render 'search_form', q: @q, url: articles_path %>
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>質問タイトル</th>
          <th>質問内容</th>
          <th>質問回答</th>
          <th>質問作成日</th>
          <th>質問更新日</th>
        </tr>
      </thead>
      <% @articles.each do |article| %>
        <%= render article %>
      <% end %>
    </table>
  <%= paginate @articles, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/articles/new.html.erb
<div class = container>
  <h1>新規質問投稿</h1>
  <div class="card">
  <div class="card-header">
      新規質問投稿
  </div>
  <div class="card-body">
    <h5 class="card-title">石綿・産廃に関する質問投稿</h5>
    <%= render "form", article: @article %>
  </div>
  <div class="card-footer">
    <%= link_to "質問一覧へ戻る", articles_path,class: "btn btn-primary" %>
  </div>
  </div>
</div>

app/views/articles/search.html.erb
<div data-controller="autocomplete">
<ul data-autocomplete-target="results">
<% @articles.each do |article| %>
  <li class="w-80 flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-blue-200 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-blue-200 dark:hover:text-gray-300" role="option" data-autocomplete-value="<%= article.id %>" data-autocomplete-label="<%= article.title %>">
    <%= article.title %>
  </li>
<% end %>
</ul>
</div>

app/views/articles/show.html.erb
<div class = container>
  <p style="color: green"><%= notice %></p>
  <div class= "card">
    <div class= "row">
      <div class="card-header d-flex justify-content col-12">
        <div class = "title mx-3">
        質問詳細
        </div>
        <%= render 'bookmark_buttons', { article: @article } %>
        ブックマーク
        <%= render 'like_buttons', { article: @article } %>
      評価する
      <%= @total_likes%>
      </div>
      <div class="card-body col-12">
        <h5 class="card-title">石綿産廃に関する質問詳細</h5>
        <p class="card-text"><%= "質問タイトル:#{@article.title}" %></p>
        <p class="card-text"><%= "質問内容:#{@article.question_body}" %></p>
        <p class="card-text"><%= "質問回答:#{@article.question_answer}" %></p>
      </div>
      <div class="card-footer col-12">
        <% if logged_in? && (current_user.own?(@article) || current_user.admin?)%>
        <%= link_to "編集", edit_article_path(@article),class: "btn btn-primary" %>
        <%= link_to "削除", @article, data: { turbo_method: :delete, turbo_confirm: "削除しますか？" },class: "btn btn-primary" %>
        <% end%>
        <%= link_to "一覧に戻る", articles_path,class: "btn btn-primary"%>
        </div>
    </div>
  </div>
</div>