config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/terms_of_service'
  resources :users, only: %i[new create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles,only: %i[index new create show edit update destroy] do
    collection do
      get :search
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :article_likes, only: %i[create destroy]
  namespace :admin do
    root "articles#index"
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => "user_sessions#create"
    delete 'logout' => 'user_sessions#destroy', :as => :logout
    resources :articles, only: %i[new index edit update show destroy create]
  end
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'articles#index'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 255 }
  
  #記事との関連付け
  has_many :articles, dependent: :destroy

  #ブックマーク機能の関連付け
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_articles, through: :bookmarks, source: :article
  
  #いいね機能の関連付け
  has_many :article_likes, dependent: :destroy
  has_many :liked_articles, through: :article_likes, source: :article

  #一般ユーザーと管理者ユーザーの分類
  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object&.user_id
  end
  
  #ブックマークを追加するメソッド
  def bookmark(article)
    bookmark_articles << article
  end

  #ブックマークを削除するメソッド
  def unbookmark(article)
    bookmark_articles.destroy(article)
  end

  #すでにブックマークしているか確認するメソッド
  def bookmark?(article)
    bookmark_articles.include?(article)
  end

  #いいねを追加する機能
  def like(article)
    liked_articles << article
  end

  #いいねを削除する機能
  def unlike(article)
    liked_articles.destroy(article)
  end 

  #いいねがすでにされていないか確認する機能
  def liked?(article)
    liked_articles.include?(article)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10 col-lg-8 mx-auto'>
      <h1>ユーザー登録</h1>
      <%= form_with model: @user do |f| %>
        <div class='form-group'>
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :email,'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :password, 'パスワード'%>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :password_confirmation,'パスワード確認' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '利用規約に同意し登録', class: 'btn btn-primary mr-3' %>
        <%= link_to '利用規約確認' ,terms_of_service_path, class: 'mx-3'%>
        <%= link_to '個人情報保護方針確認' ,privacy_policy_path, class: 'mx-3'%>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>