config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/terms_of_service'
  resources :users, only: %i[new create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles,only: %i[index new create show edit update destroy] do
    collection do
      get :search
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :article_likes, only: %i[create destroy]
  namespace :admin do
    root "articles#index"
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => "user_sessions#create"
    delete 'logout' => 'user_sessions#destroy', :as => :logout
    resources :articles, only: %i[new index edit update show destroy create]
  end
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'articles#index'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= 'helpEcofaq' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class="nav-item">
          <%= link_to "質問一覧", articles_path,class: 'nav-link' %>
          <%= link_to 'ログイン', login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom d-flex justify-content-start mx-5'>
        <div class='copyright '>
          <p>Copyright © 2024. taikimatsumoto</p>
        </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
      <li class="nav-item">
      <%= link_to "質問投稿", new_article_path, class:"mx-1" %>
      <%= link_to "質問一覧", articles_path,class:"mx-1" %>
      <%= link_to "お気に入りリスト", bookmarks_articles_path,class:"mx-1" %>
      <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete } ,class:"mx-1"%>
      <li>
      </ul>
    </div>
  </nav>
</header>